---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    rsync: https://github.com/simp/pupmod-simp-rsync.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    selinux_core: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
  symlinks:
    dhcp: "#{source_dir}"
